# Generated by Django 3.2 on 2021-04-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyRates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='default',
        ),
        migrations.AddField(
            model_name='provider',
            name='priority',
            field=models.BooleanField(default=False, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
